// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQF3lF3nfQ1bPjX_TcjRMZxHBdvie-lJI',
    appId: '1:1002532399609:web:68f19ffa57f775a39df528',
    messagingSenderId: '1002532399609',
    projectId: 'heroic-gamma-268212',
    authDomain: 'heroic-gamma-268212.firebaseapp.com',
    storageBucket: 'heroic-gamma-268212.firebasestorage.app',
    measurementId: 'G-JFYPZYJBFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQYfgmJaQARDif2L2q-NPi8O1HntjSkEc',
    appId: '1:1002532399609:android:89f6d34937f3f1de9df528',
    messagingSenderId: '1002532399609',
    projectId: 'heroic-gamma-268212',
    storageBucket: 'heroic-gamma-268212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKToq1lB822-ddr3ZL6QMNPVgPSZaR2bQ',
    appId: '1:1002532399609:ios:2e6d832650ec64b49df528',
    messagingSenderId: '1002532399609',
    projectId: 'heroic-gamma-268212',
    storageBucket: 'heroic-gamma-268212.firebasestorage.app',
    androidClientId:
        '1002532399609-6spr8ma3f3vak7r70ipi0faq3skpgsb8.apps.googleusercontent.com',
    iosClientId:
        '1002532399609-ev7pm44g258c09ulv2nkakioe60iluf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezanVaktiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKToq1lB822-ddr3ZL6QMNPVgPSZaR2bQ',
    appId: '1:1002532399609:ios:2e6d832650ec64b49df528',
    messagingSenderId: '1002532399609',
    projectId: 'heroic-gamma-268212',
    storageBucket: 'heroic-gamma-268212.firebasestorage.app',
    androidClientId:
        '1002532399609-6spr8ma3f3vak7r70ipi0faq3skpgsb8.apps.googleusercontent.com',
    iosClientId:
        '1002532399609-ev7pm44g258c09ulv2nkakioe60iluf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezanVaktiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQF3lF3nfQ1bPjX_TcjRMZxHBdvie-lJI',
    appId: '1:1002532399609:web:31a5171de2d056c89df528',
    messagingSenderId: '1002532399609',
    projectId: 'heroic-gamma-268212',
    authDomain: 'heroic-gamma-268212.firebaseapp.com',
    storageBucket: 'heroic-gamma-268212.firebasestorage.app',
    measurementId: 'G-T30VFLCY46',
  );
}
